### ISSUE TITLE
RFC 2141 compliance

### ISSUE THREAD

**Issue by mudge** [altmetric/urn#2]
Can we fully implement compliance with [RFC 2141](https://www.ietf.org/rfc/rfc2141.txt), specifically:
1. Namespace Identifier Syntax;
2. Namespace Specific Syntax;
3. Canonical form;
4. Lexical equivalence.

From 1 and 2, we could provide getters for the NID and NSS portions of the URN (e.g. `urn.nid`, `urn.nss`).

From 3, we could truly normalise URNs (e.g. `urn.canonical`).

From 4, we could implement strict equality between `URN` instances; optionally providing a more relaxed equality considering `%`-escaping.

**Comment by mudge** [comment]
A potential "strict" regular expression as taken from the RFC: `/[uU][rR][nN]:(?<nid>[A-Za-z0-9][A-Z-a-z0-9-]{1,31}):(?<nss>(?:[A-Za-z0-9()+,-.:=@;$_!*']|%[0-9A-Fa-f]{2})+)/`

**Comment by jbilbo** [comment]
Yes, we should go towards this.

About the regex: It's not fully compliant as it allows `urn` as a valid `nid`, but it's a very good start!

> To avoid confusion with the "urn:" identifier, the NID "urn" is reserved and MUST NOT be used.

Note: Although it doesn't affect to the result, there's a duplicate `-` in the `nid` part.

**Comment by mudge** [comment]
Good catch: we could probably use an extended regular expression (viz. with comments) to make this a bit clearer.

``` ruby
%r{
  urn:
  (?<nid>
    (?!urn) # the NID "urn" is reserved and MUST NOT be used
    [A-Za-z0-9] # let-num
    [A-Za-z0-9-]{1,31} # let-num-hyp
  )
  :
  (?<nss>
    (?: # URN chars
      [A-Za-z0-9()+,-.:=@;$_!*'] # trans
      |
      %[0-9A-Fa-f]{2} # hex
    )+
  )
}xi
```

We could also use character classes such as `\p{Alnum}` but I'm not sure that makes it any clearer.

**Comment by ascastro** [comment]
Since the regex is in ignore case mode, should we remove one of the letter intervals from the regex? either `A-Z` or `a-z`? Same for `A-F` or `a-f`.

**Comment by mudge** [comment]
@ascastro that makes sense: I had the upper and lowercase when the pattern was case-sensitive (so that it more closely matched the RFC's grammar) but switched to case-insensitivity so I could drop the weird looking `[uU][rR][nN]`.

Maybe we should simplify it further but I'm keen not to lose the connection to the official specification.

**Comment by ascastro** [comment]
yep, I agree that we should match the official spec

**Comment by jbilbo** [comment]
About the regex, we shouldn't allow this:

`urn:urn:123`

But we still should allow this:

`urn:urn123:123`

**Comment by ascastro** [comment]
we can replace the look ahead bit with `(?!urn:)` instead, and that will solve that problem

**Comment by jbilbo** [comment]
> we can replace the look ahead bit with (?!urn:) instead, and that will solve that problem

Then the named group (`?<nid>`) is not valid as it includes the `:`?

**Comment by mudge** [comment]
We might be able to use [the best regex trick](http://www.rexegg.com/regex-best-trick.html) to do this if zero-width lookaheads and lookbehinds don't work:

``` ruby
%r{
  urn:
  (?:
    urn # the NID "urn" is reserved and MUST NOT be used
    |
    (?<nid>
      [a-z0-9] # let-num
      [a-z0-9-]{1,31} # let-num-hyp
    )
  )
  :
  (?<nss>
    (?: # URN chars
      [A-Za-z0-9()+,-.:=@;$_!*'] # trans
      |
      %[0-9A-Fa-f]{2} # hex
    )+
  )
}xi
```

This would mean that we still _match_ something with a NID of `urn` but when you tried to extract that named group, it will be `nil`.

**Comment by jbilbo** [comment]
> Then the named group (?<nid>) is not valid as it includes the :?

I was wrong with this. 

This works like a charm:

``` ruby
%r{
  urn:
  (?<nid>
    (?!urn:) # the NID "urn" is reserved and MUST NOT be used
    [A-Za-z0-9] # let-num
    [A-Za-z0-9-]{1,31} # let-num-hyp
  )
  :
  (?<nss>
    (?: # URN chars
      [A-Za-z0-9()+,-.:=@;$_!*'] # trans
      |
      %[0-9A-Fa-f]{2} # hex
    )+
  )
}xi
```

**Comment by mudge** [comment]
Note that named captures in a regular expression requires Ruby 1.9 so, were we to swap to using the above pattern, we'd have to drop support for 1.8.7 (which is totally reasonable unless we're happy to use numbered captures instead).

**Comment by jbilbo** [comment]
I'm OK dropping support to 1.8.7, readability is more important.

**Comment by jbilbo** [comment]
There's a clause we miss from RFC2141:

> 2.4 Excluded characters
> The following list is included only for the sake of completeness.
>    Any octets/characters on this list are explicitly NOT part of the URN character set, and if used in an URN, MUST be %encoded:
> 
> ```
>    <excluded> ::= octets 1-32 (1-20 hex) | "\" | """ | "&" | "<"
>                   | ">" | "[" | "]" | "^" | "`" | "{" | "|" | "}" | "~"
>                   | octets 127-255 (7F-FF hex)
> ```
> 
>   In addition, octet 0 (0 hex) should NEVER be used, in either unencoded or %-encoded form.
>   An URN ends when an octet/character from the excluded character set (<excluded>) is encountered. The character from the excluded character set is NOT part of the URN.

Specifically: we don't exclude `octets 1-32 (1-20 hex)` and `octet 0 (0 hex)`

**Comment by jbilbo** [comment]
This `PATTERN` should do the trick:

``` ruby
  PATTERN = %{(?i:urn:(?!urn:)[a-z0-9][a-z0-9\-]{1,31}:} +
            %{(?:[a-z0-9()+,-.:=@;$_!*']|%([2][1-9a-f]|[3-9a-f][0-9a-f]))+)}.freeze

```
